# Utilise l'image de base Alpine
FROM alpine

# Spécifie un volume à l'emplacement /data
VOLUME /data

# Utilise la commande CMD pour afficher "Hello, World!" lorsque le conteneur s'exécute
CMD ["echo", "Hello, World!"]
